// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vizallasuj2.Data;

#nullable disable

namespace Vizallasuj2.Migrations
{
    [DbContext(typeof(vizDbContext))]
    partial class vizDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Vizallasuj2.Models.Víz", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Folyo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Varos")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Vizallas")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Vízállás");
                });
#pragma warning restore 612, 618
        }
    }
}
